// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using br_H60L02.Models;

#nullable disable

namespace br_H60L02.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("br_H60L02.Models.Genre", b =>
                {
                    b.Property<long>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1L,
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreId = 2L,
                            GenreName = "Comedy"
                        },
                        new
                        {
                            GenreId = 3L,
                            GenreName = "Romance"
                        },
                        new
                        {
                            GenreId = 4L,
                            GenreName = "SitCom"
                        },
                        new
                        {
                            GenreId = 5L,
                            GenreName = "Action"
                        });
                });

            modelBuilder.Entity("br_H60L02.Models.Movie", b =>
                {
                    b.Property<long>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MovieId"));

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1L,
                            Rating = 99.0m,
                            Title = "Deadpool"
                        },
                        new
                        {
                            MovieId = 2L,
                            Rating = 99.0m,
                            Title = "Deadpool 2"
                        },
                        new
                        {
                            MovieId = 3L,
                            Rating = 99.0m,
                            Title = "Deadpool 3"
                        },
                        new
                        {
                            MovieId = 4L,
                            Rating = 99.0m,
                            Title = "Fast and Furious"
                        },
                        new
                        {
                            MovieId = 5L,
                            Rating = 99.0m,
                            Title = "Fast and Furious 2"
                        },
                        new
                        {
                            MovieId = 6L,
                            Rating = 99.0m,
                            Title = "Fast and Furious 3"
                        },
                        new
                        {
                            MovieId = 7L,
                            Rating = 99.0m,
                            Title = "Fast and Furious 4"
                        },
                        new
                        {
                            MovieId = 8L,
                            Rating = 99.0m,
                            Title = "Fast and Furious 5"
                        },
                        new
                        {
                            MovieId = 9L,
                            Rating = 99.0m,
                            Title = "Fast and Furious 6"
                        },
                        new
                        {
                            MovieId = 10L,
                            Rating = 99.0m,
                            Title = "Fast and Furious 7"
                        },
                        new
                        {
                            MovieId = 11L,
                            Rating = 99.0m,
                            Title = "Fast and Furious 8"
                        },
                        new
                        {
                            MovieId = 12L,
                            Rating = 99.0m,
                            Title = "Fast and Furious 9"
                        });
                });

            modelBuilder.Entity("br_H60L02.Models.MovieGenre", b =>
                {
                    b.Property<long>("MovieGenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MovieGenreId"));

                    b.Property<long>("GenreId")
                        .HasColumnType("bigint");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint");

                    b.HasKey("MovieGenreId");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("MoviesGenres");
                });

            modelBuilder.Entity("br_H60L02.Models.MovieGenre", b =>
                {
                    b.HasOne("br_H60L02.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("br_H60L02.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("br_H60L02.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("br_H60L02.Models.Movie", b =>
                {
                    b.Navigation("MovieGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
